### 1.Initialization

In [79]:
import numpy as np

In [80]:
np.zeros(3)

array([0., 0., 0.])

In [81]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [82]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [83]:
np.ones((2,2,4), dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [84]:
np.full((2,2),"Curry")

array([['Curry', 'Curry'],
       ['Curry', 'Curry']], dtype='<U5')

In [85]:
np.random.rand(3)

array([0.25895855, 0.39488834, 0.99142569])

In [86]:
np.random.rand(3,4)

array([[0.41832317, 0.26644694, 0.41392099, 0.49668239],
       [0.41891808, 0.750813  , 0.57712065, 0.3508871 ],
       [0.7321447 , 0.80635859, 0.48268748, 0.60653027]])

In [87]:
np.random.randn(3)

array([-2.03724338,  0.1527959 , -0.50388713])

In [88]:
np.random.randn(3,4)

array([[ 0.02143861,  0.51526565,  0.30883244,  0.63512164],
       [ 1.14851885, -0.08385759, -1.14112302, -0.12143479],
       [-0.94597363, -0.74126307, -0.79494079, -1.80981722]])

In [89]:
np.random.randint(5,10,size=(10,10))

array([[7, 9, 5, 6, 5, 7, 5, 8, 7, 5],
       [7, 9, 8, 7, 8, 5, 9, 9, 8, 9],
       [9, 5, 8, 5, 7, 8, 5, 8, 8, 8],
       [8, 9, 5, 5, 7, 5, 5, 8, 9, 9],
       [6, 8, 8, 8, 6, 6, 7, 9, 9, 6],
       [5, 8, 5, 5, 6, 7, 6, 5, 5, 6],
       [7, 5, 5, 5, 8, 5, 9, 8, 9, 9],
       [6, 9, 9, 9, 5, 6, 8, 5, 5, 6],
       [8, 9, 6, 9, 6, 7, 7, 7, 9, 7],
       [7, 8, 6, 8, 8, 8, 8, 7, 9, 8]])

In [90]:
np.random.randint(8,200)

162

### 2.Slice of NumPy 

In [91]:
data = np.random.randint(5,10,(10,10))
data[4:8]

array([[7, 6, 8, 6, 6, 6, 7, 6, 9, 7],
       [8, 9, 5, 6, 7, 8, 9, 9, 5, 6],
       [5, 9, 6, 7, 5, 5, 6, 6, 8, 6],
       [8, 7, 5, 6, 7, 9, 8, 6, 9, 9]])

In [92]:
data[4:8,4:6]

array([[6, 6],
       [7, 8],
       [5, 5],
       [7, 9]])

In [93]:
data[4:6,4:6]

array([[6, 6],
       [7, 8]])

### 3.Combine Data

In [94]:
data1 = np.random.randint(5,15,size=(5,3))
data1

array([[ 5, 11,  7],
       [14,  7, 13],
       [ 7, 12,  9],
       [ 7,  6,  6],
       [ 7, 14,  5]])

In [95]:
data2 = np.random.randint(5,15,size=(5,3))
data2

array([[13, 14,  8],
       [ 6,  5,  5],
       [14, 10, 12],
       [ 8, 11,  5],
       [ 6, 10,  5]])

In [96]:
# 横向拼接
print(np.hstack([data1,data2]))

print(np.concatenate([data1, data2], axis=1))

[[ 5 11  7 13 14  8]
 [14  7 13  6  5  5]
 [ 7 12  9 14 10 12]
 [ 7  6  6  8 11  5]
 [ 7 14  5  6 10  5]]
[[ 5 11  7 13 14  8]
 [14  7 13  6  5  5]
 [ 7 12  9 14 10 12]
 [ 7  6  6  8 11  5]
 [ 7 14  5  6 10  5]]


In [97]:
# 纵向拼接
print(np.vstack([data1, data2]))

print(np.concatenate([data1,data2],axis=0))

[[ 5 11  7]
 [14  7 13]
 [ 7 12  9]
 [ 7  6  6]
 [ 7 14  5]
 [13 14  8]
 [ 6  5  5]
 [14 10 12]
 [ 8 11  5]
 [ 6 10  5]]
[[ 5 11  7]
 [14  7 13]
 [ 7 12  9]
 [ 7  6  6]
 [ 7 14  5]
 [13 14  8]
 [ 6  5  5]
 [14 10 12]
 [ 8 11  5]
 [ 6 10  5]]


In [98]:
data1 = np.random.randint(5,15,size=(5,3,2))
data1

array([[[ 6, 14],
        [14,  9],
        [11,  7]],

       [[ 8,  9],
        [13, 10],
        [13,  8]],

       [[ 8,  6],
        [10, 13],
        [ 7, 11]],

       [[ 8,  6],
        [ 7,  6],
        [13,  9]],

       [[11, 14],
        [ 5, 13],
        [14, 13]]])

In [99]:
data2 = np.random.randint(5,15,size=(5,3,2))
data2

array([[[ 9, 11],
        [ 7,  6],
        [ 8, 13]],

       [[11,  8],
        [13, 10],
        [ 9, 11]],

       [[13,  7],
        [13, 14],
        [ 9,  8]],

       [[ 5,  5],
        [14, 10],
        [ 9, 14]],

       [[ 7, 13],
        [12, 12],
        [ 9, 14]]])

In [100]:
np.concatenate([data1, data2], axis=2)

array([[[ 6, 14,  9, 11],
        [14,  9,  7,  6],
        [11,  7,  8, 13]],

       [[ 8,  9, 11,  8],
        [13, 10, 13, 10],
        [13,  8,  9, 11]],

       [[ 8,  6, 13,  7],
        [10, 13, 13, 14],
        [ 7, 11,  9,  8]],

       [[ 8,  6,  5,  5],
        [ 7,  6, 14, 10],
        [13,  9,  9, 14]],

       [[11, 14,  7, 13],
        [ 5, 13, 12, 12],
        [14, 13,  9, 14]]])

### 4.Splitting Data

In [101]:
data

array([[5, 9, 8, 7, 6, 9, 6, 5, 5, 6],
       [7, 5, 8, 6, 5, 5, 6, 7, 6, 6],
       [7, 7, 6, 8, 9, 5, 7, 7, 5, 7],
       [6, 8, 9, 5, 9, 9, 6, 7, 8, 8],
       [7, 6, 8, 6, 6, 6, 7, 6, 9, 7],
       [8, 9, 5, 6, 7, 8, 9, 9, 5, 6],
       [5, 9, 6, 7, 5, 5, 6, 6, 8, 6],
       [8, 7, 5, 6, 7, 9, 8, 6, 9, 9],
       [7, 5, 6, 6, 6, 6, 9, 6, 7, 6],
       [5, 7, 6, 7, 5, 8, 9, 8, 5, 8]])

In [102]:
a1,a2 = np.hsplit(data,[5])

In [103]:
a1

array([[5, 9, 8, 7, 6],
       [7, 5, 8, 6, 5],
       [7, 7, 6, 8, 9],
       [6, 8, 9, 5, 9],
       [7, 6, 8, 6, 6],
       [8, 9, 5, 6, 7],
       [5, 9, 6, 7, 5],
       [8, 7, 5, 6, 7],
       [7, 5, 6, 6, 6],
       [5, 7, 6, 7, 5]])

In [104]:
a2

array([[9, 6, 5, 5, 6],
       [5, 6, 7, 6, 6],
       [5, 7, 7, 5, 7],
       [9, 6, 7, 8, 8],
       [6, 7, 6, 9, 7],
       [8, 9, 9, 5, 6],
       [5, 6, 6, 8, 6],
       [9, 8, 6, 9, 9],
       [6, 9, 6, 7, 6],
       [8, 9, 8, 5, 8]])

In [105]:
b1,b2,b3 = np.vsplit(data,[5,7])

In [106]:
b1

array([[5, 9, 8, 7, 6, 9, 6, 5, 5, 6],
       [7, 5, 8, 6, 5, 5, 6, 7, 6, 6],
       [7, 7, 6, 8, 9, 5, 7, 7, 5, 7],
       [6, 8, 9, 5, 9, 9, 6, 7, 8, 8],
       [7, 6, 8, 6, 6, 6, 7, 6, 9, 7]])

In [107]:
b2

array([[8, 9, 5, 6, 7, 8, 9, 9, 5, 6],
       [5, 9, 6, 7, 5, 5, 6, 6, 8, 6]])

In [108]:
b3

array([[8, 7, 5, 6, 7, 9, 8, 6, 9, 9],
       [7, 5, 6, 6, 6, 6, 9, 6, 7, 6],
       [5, 7, 6, 7, 5, 8, 9, 8, 5, 8]])

### 5.Shape, Dimension

In [109]:
data.shape

(10, 10)

In [110]:
data.ndim

2

In [111]:
data.size

100

In [112]:
data.reshape(2,50)

array([[5, 9, 8, 7, 6, 9, 6, 5, 5, 6, 7, 5, 8, 6, 5, 5, 6, 7, 6, 6, 7, 7,
        6, 8, 9, 5, 7, 7, 5, 7, 6, 8, 9, 5, 9, 9, 6, 7, 8, 8, 7, 6, 8, 6,
        6, 6, 7, 6, 9, 7],
       [8, 9, 5, 6, 7, 8, 9, 9, 5, 6, 5, 9, 6, 7, 5, 5, 6, 6, 8, 6, 8, 7,
        5, 6, 7, 9, 8, 6, 9, 9, 7, 5, 6, 6, 6, 6, 9, 6, 7, 6, 5, 7, 6, 7,
        5, 8, 9, 8, 5, 8]])

In [113]:
d = np.array([1,2,3,4,5,6,7,9])

In [114]:
d.ndim

1

In [115]:
d.shape

(8,)

In [116]:
d.size

8

In [117]:
d.reshape(8,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [9]])

In [118]:
d.reshape(8,-1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [9]])

In [119]:
data.reshape(-1,20)

array([[5, 9, 8, 7, 6, 9, 6, 5, 5, 6, 7, 5, 8, 6, 5, 5, 6, 7, 6, 6],
       [7, 7, 6, 8, 9, 5, 7, 7, 5, 7, 6, 8, 9, 5, 9, 9, 6, 7, 8, 8],
       [7, 6, 8, 6, 6, 6, 7, 6, 9, 7, 8, 9, 5, 6, 7, 8, 9, 9, 5, 6],
       [5, 9, 6, 7, 5, 5, 6, 6, 8, 6, 8, 7, 5, 6, 7, 9, 8, 6, 9, 9],
       [7, 5, 6, 6, 6, 6, 9, 6, 7, 6, 5, 7, 6, 7, 5, 8, 9, 8, 5, 8]])

### 6.Utility Function

In [120]:
np.sum(data)

679

In [121]:
np.sum(data, axis=1)

array([66, 61, 68, 75, 68, 72, 63, 74, 64, 68])

In [122]:
np.sum(data, axis=0)

array([65, 72, 67, 64, 65, 70, 73, 67, 67, 69])

In [123]:
data

array([[5, 9, 8, 7, 6, 9, 6, 5, 5, 6],
       [7, 5, 8, 6, 5, 5, 6, 7, 6, 6],
       [7, 7, 6, 8, 9, 5, 7, 7, 5, 7],
       [6, 8, 9, 5, 9, 9, 6, 7, 8, 8],
       [7, 6, 8, 6, 6, 6, 7, 6, 9, 7],
       [8, 9, 5, 6, 7, 8, 9, 9, 5, 6],
       [5, 9, 6, 7, 5, 5, 6, 6, 8, 6],
       [8, 7, 5, 6, 7, 9, 8, 6, 9, 9],
       [7, 5, 6, 6, 6, 6, 9, 6, 7, 6],
       [5, 7, 6, 7, 5, 8, 9, 8, 5, 8]])

In [124]:
np.sin(data)

array([[-0.95892427,  0.41211849,  0.98935825,  0.6569866 , -0.2794155 ,
         0.41211849, -0.2794155 , -0.95892427, -0.95892427, -0.2794155 ],
       [ 0.6569866 , -0.95892427,  0.98935825, -0.2794155 , -0.95892427,
        -0.95892427, -0.2794155 ,  0.6569866 , -0.2794155 , -0.2794155 ],
       [ 0.6569866 ,  0.6569866 , -0.2794155 ,  0.98935825,  0.41211849,
        -0.95892427,  0.6569866 ,  0.6569866 , -0.95892427,  0.6569866 ],
       [-0.2794155 ,  0.98935825,  0.41211849, -0.95892427,  0.41211849,
         0.41211849, -0.2794155 ,  0.6569866 ,  0.98935825,  0.98935825],
       [ 0.6569866 , -0.2794155 ,  0.98935825, -0.2794155 , -0.2794155 ,
        -0.2794155 ,  0.6569866 , -0.2794155 ,  0.41211849,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.95892427, -0.2794155 ,  0.6569866 ,
         0.98935825,  0.41211849,  0.41211849, -0.95892427, -0.2794155 ],
       [-0.95892427,  0.41211849, -0.2794155 ,  0.6569866 , -0.95892427,
        -0.95892427, -0.2794155 , -0.2794155 

In [125]:
data.T

array([[5, 7, 7, 6, 7, 8, 5, 8, 7, 5],
       [9, 5, 7, 8, 6, 9, 9, 7, 5, 7],
       [8, 8, 6, 9, 8, 5, 6, 5, 6, 6],
       [7, 6, 8, 5, 6, 6, 7, 6, 6, 7],
       [6, 5, 9, 9, 6, 7, 5, 7, 6, 5],
       [9, 5, 5, 9, 6, 8, 5, 9, 6, 8],
       [6, 6, 7, 6, 7, 9, 6, 8, 9, 9],
       [5, 7, 7, 7, 6, 9, 6, 6, 6, 8],
       [5, 6, 5, 8, 9, 5, 8, 9, 7, 5],
       [6, 6, 7, 8, 7, 6, 6, 9, 6, 8]])

In [126]:
data.mean(axis=1)

array([6.6, 6.1, 6.8, 7.5, 6.8, 7.2, 6.3, 7.4, 6.4, 6.8])

In [127]:
data.std(axis=1)

array([1.49666295, 0.94339811, 1.16619038, 1.36014705, 0.9797959 ,
       1.53622915, 1.26885775, 1.356466  , 1.0198039 , 1.4       ])

### 7.Broadcasting

In [128]:
v = np.array([1,2,3,4,5])

In [129]:
s = 10

In [130]:
v+s

array([11, 12, 13, 14, 15])

In [131]:
a = np.array([[1],[2],[3],[4],[5]])

In [132]:
a.shape

(5, 1)

In [133]:
a + v

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])